### PR TITLE
Removed generated openmrs folder in examples

### PR DESCRIPTION
**Pull request by rrameshbtech**
* Added openmrs folder to .gitignore
* Deleted openmrs folder from examples root folder

### CODE REVIEW

**Comment by joeldenning** [comment]
I think there is value in having the dist files in versino control as a demo of what the directory looks like. I link people to it when they're trying to understand what packmap.

**Comment by rrameshbtech** [comment]
I think this can be seen just by running `npm run build` command. Also adding generated files in git will not be good idea, as it will show the diff in git whenever anybody runs `build` command.

**Comment by joeldenning** [comment]
I am aware of the consequences of putting the build directory into version control -- and I did it on purpose anyway because I think it is worth it. 

For people exploring the project, having to clone the repo and run `npm install && npm run build` in order to understand what the project even does is not ideal. Additionally, if the files are not in version control, we cannot link people to github to view what the openmrs/frontend directory is supposed to look like.

I maintain a few dozen open source projects, and usually I do not put built files into version control. However, in this case I think it's the easiest way for people to actually understand what the project does.

**Comment by rrameshbtech** [comment]
Closing it as it is expected as per joel's above comment

**Pull request closed without merging**
